# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Geekwise PHP'
tagline:          'Ken Koontz'
description:      'Geekwise Academy PHP introductory course.'
url:              http://lanyon.getpoole.com
baseurl:          http://kennethkoontz.github.io/php.course/
paginate:         5

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
